name: Bug Report
description: Create a report to help us improve
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. See error
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: OS
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true

  - type: dropdown
    id: mode
    attributes:
      label: Mode
      options:
        - Singleplayer
        - Multiplayer
    validations:
      required: true

  - type: dropdown
    id: server-settings
    attributes:
      label: Server Settings
      options:
        - "N/A"
        - Host
        - Dedicated
    validations:
      required: true

  - type: input
    id: game-version
    attributes:
      label: Game Version
      placeholder: "e.g. 42.17.1"
    validations:
      required: true

  - type: input
    id: mod-version
    attributes:
      label: Mod Version
      placeholder: "e.g. 1.2.2"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "Error from console.txt"
      description: Paste the error you found.
      render: shell
    validations:
      required: false